import React from "react";
import {AbsoluteFill,Audio,Img,Sequence,Video,interpolate,spring,staticFile,useCurrentFrame,useVideoConfig} from "remotion";
import {VIETNAMESE_FONT_FAMILY,useVietnameseFont,vietnameseFontFaceCss} from "./components/vietnameseFont";

const FPS=30;
const NAVY="#090e16";
const GOLD="#ffb63d";
const CYAN="#28d7f4";
type Cue={from:number;to:number;text:string};
type Ad={id:string;duration:number;hook:string;cues:Cue[];joins:number[];joinLabels:string[];assets:string[]};

const ads:Ad[]=[
 {id:"ad01",duration:44.20,hook:"HỌC NHIỀU VẪN MẤT GỐC?",joins:[10.50,30.80,35.46],joinLabels:["ĐỪNG VỘI NGHĨ CON LƯỜI","HỌC LẠI ĐÚNG PHẦN BỊ HỔNG","BÍ MẬT LẤY GỐC TIẾNG ANH"],assets:["staging/brisky-generated-v3/01-vocabulary-forgotten.png","staging/brisky-real/05-class-lesson.jpg","staging/brisky-generated-v3/04-level-assessment.png"],cues:[
  {from:.02,to:1.52,text:"Cứ nhắc tới tiếng Anh là sợ"},{from:1.86,to:2.72,text:"Học trước quên sau"},{from:3.10,to:5.82,text:"Gặp bài kiểm tra trên lớp lại rất nản"},{from:6.46,to:8.96,text:"Ba mẹ cho con học thêm nhiều nơi"},{from:9.10,to:10.48,text:"Nhưng vẫn chưa cải thiện"},
  {from:10.52,to:13.72,text:"Ba mẹ đừng vội nghĩ con lười hay kém"},{from:14.98,to:17.34,text:"Nhiều bạn không phải không có khả năng"},{from:17.72,to:20.58,text:"Con đã hổng kiến thức và mất gốc"},{from:20.58,to:23.60,text:"Tình trạng mất gốc kéo dài quá lâu"},{from:23.60,to:26.30,text:"Nhưng chưa được học lại"},{from:26.30,to:28.30,text:"một cách đúng đắn"},{from:28.30,to:30.78,text:"Học từ vựng hôm nay, mai đã quên"},
  {from:30.82,to:33.02,text:"Thầy và đội ngũ tổ chức chương trình"},{from:33.02,to:35.44,text:"Bí mật lấy gốc tiếng Anh cho con"},{from:35.50,to:39.92,text:"Ba mẹ chỉ cần nhấn vào link bên dưới"},{from:40.20,to:44.16,text:"Đội ngũ giáo viên sẽ liên hệ hỗ trợ"}
 ]},
 {id:"ad02",duration:48.14,hook:"TỪ 3–4 ĐIỂM LÊN 8 ĐIỂM",joins:[4.72,11.84,23.42,38.54],joinLabels:["MỘT HỌC SINH LỚP 7 MẤT GỐC","KẾT QUẢ: 8 ĐIỂM TIẾNG ANH","LỘ TRÌNH ĐÃ ĐƯỢC ĐÚC RÚT","3 BUỔI ZOOM DÀNH CHO CHA MẸ"],assets:["staging/brisky-real/07-brisky-students.jpg","staging/brisky-generated-v2/03-confident-student.png","staging/brisky-real/04-brisky-teachers.jpg","staging/brisky-generated-v3/04-level-assessment.png"],cues:[
  {from:.02,to:2.20,text:"Đây là câu chuyện của một người mẹ"},{from:2.20,to:4.70,text:"có con lớp 7 bị mất gốc tiếng Anh"},{from:4.74,to:8.50,text:"Người mẹ chia sẻ niềm hạnh phúc"},{from:8.50,to:11.82,text:"khi con đạt 8 điểm tiếng Anh"},
  {from:11.86,to:15.90,text:"Từ một học sinh chỉ đạt 3–4 điểm"},{from:15.90,to:19.20,text:"con đã vươn lên đạt 8 điểm"},{from:19.20,to:23.40,text:"Đó là cả một quá trình nỗ lực"},
  {from:23.44,to:28.50,text:"Thầy trực tiếp giảng dạy học sinh mất gốc"},{from:28.50,to:33.00,text:"và đúc rút một lộ trình học tập"},{from:33.00,to:36.00,text:"chia sẻ trong 3 buổi Zoom"},{from:36.00,to:38.52,text:"cho cha mẹ có con lớp 3–9"},
  {from:38.56,to:41.40,text:"Nếu ba mẹ thật sự quan tâm"},{from:41.40,to:44.20,text:"hãy để lại số điện thoại"},{from:44.20,to:46.20,text:"hoặc nhấn vào link bên dưới"},{from:46.20,to:48.12,text:"để nhận hướng dẫn tham gia"}
 ]},
 {id:"ad03",duration:48.24,hook:"DẤU HIỆU CON ĐANG HỔNG GỐC",joins:[8.50,23.04,38.40],joinLabels:["BA MẸ CẦN CHÚ Ý","THUỘC NHƯNG KHÓ ÁP DỤNG","3 BUỔI ZOOM • LỚP 3 ĐẾN LỚP 9"],assets:["staging/brisky-generated-v3/02-long-reading.png","staging/brisky-generated-v3/03-grammar-application.png","staging/brisky-real/07-brisky-students.jpg"],cues:[
  {from:.02,to:2.50,text:"Trước mỗi bài kiểm tra tiếng Anh"},{from:2.50,to:4.70,text:"ba mẹ luôn hồi hộp, lo lắng"},{from:4.70,to:6.60,text:"không biết con làm được bài"},{from:6.60,to:8.48,text:"hay lại bị điểm kém"},
  {from:8.52,to:11.20,text:"Học từ vựng hôm nay"},{from:11.20,to:12.60,text:"ngày mai đã quên"},{from:12.60,to:15.30,text:"Gặp bài đọc dài là ngại"},{from:15.30,to:18.10,text:"Làm bài chỉ khoanh theo cảm tính"},{from:18.10,to:20.40,text:"Học thuộc ngữ pháp"},{from:20.40,to:23.02,text:"nhưng không biết áp dụng"},
  {from:23.06,to:26.80,text:"Sau nhiều năm trực tiếp giảng dạy"},{from:26.80,to:30.80,text:"học sinh mất gốc tiếng Anh"},{from:30.80,to:34.20,text:"thầy tổ chức chương trình 3 buổi Zoom"},{from:34.20,to:38.38,text:"cho cha mẹ có con lớp 3–9"},
  {from:38.42,to:41.10,text:"Nếu ba mẹ quan tâm"},{from:41.10,to:43.30,text:"hãy nhấn đường link bên dưới"},{from:43.30,to:45.80,text:"để nhận món quà"},{from:45.80,to:48.20,text:"và lộ trình từ Brisky"}
 ]},
 {id:"ad04",duration:49.36,hook:"CON ĐANG HỔNG PHẦN NÀO?",joins:[4.12,17.18,21.42,32.48,37.42,42.60],joinLabels:["HỔNG TỪ VỰNG","HỔNG CÂU ĐƠN","HỔNG NGỮ PHÁP","HỔNG ĐỌC HIỂU","BÍ MẬT LẤY GỐC TIẾNG ANH","3 BUỔI ZOOM CHO CHA MẸ"],assets:["staging/brisky-generated-v3/01-vocabulary-forgotten.png","staging/brisky-generated-v2/01-teacher-guiding-student.png","staging/brisky-generated-v3/03-grammar-application.png","staging/brisky-generated-v3/02-long-reading.png","staging/brisky-real/04-brisky-teachers.jpg","staging/brisky-generated-v3/04-level-assessment.png"],cues:[
  {from:.02,to:2.10,text:"Có bạn bị hổng từ vựng"},{from:2.10,to:4.10,text:"học hôm nay, mai lại quên"},{from:4.14,to:7.40,text:"Có bạn lại hổng câu đơn"},{from:7.40,to:10.60,text:"biết từ nhưng không biết"},{from:10.60,to:14.20,text:"làm thế nào để ghép thành câu"},{from:14.20,to:17.16,text:"Từ vựng biết nhưng câu vẫn hổng"},
  {from:17.20,to:19.20,text:"Có bạn hổng ngữ pháp"},{from:19.20,to:21.40,text:"học rồi nhưng khó áp dụng"},{from:21.44,to:24.00,text:"Có bạn lại hổng đọc hiểu"},{from:24.00,to:27.60,text:"biết từng từ, từng câu"},{from:27.60,to:32.46,text:"nhưng không hiểu được cả đoạn"},
  {from:32.50,to:34.80,text:"Thầy Quyền và đội ngũ"},{from:34.80,to:37.40,text:"tổ chức Bí mật lấy gốc tiếng Anh"},{from:37.44,to:39.80,text:"Đây là 3 buổi Zoom online"},{from:39.80,to:42.58,text:"cho cha mẹ có con lớp 3–9"},{from:42.62,to:45.50,text:"Ba mẹ hãy nhấn nút đăng ký"},{from:45.50,to:49.34,text:"và để lại thông tin tham gia"}
 ]},
 {id:"ad05",duration:49.62,hook:"ĐỪNG VỘI GẮN NHÃN CON LƯỜI",joins:[7.66,15.42,21.58,31.60,40.78],joinLabels:["ĐIỂM THẤP KHÔNG CÓ NGHĨA LÀ LƯỜI","CON ĐANG THIẾU ĐỊNH HƯỚNG","3 BUỔI ZOOM CỦA BRISKY","LỘ TRÌNH TỪ CƠ BẢN ĐẾN NÂNG CAO","NHẤN ĐĂNG KÝ BÊN DƯỚI"],assets:["staging/brisky-generated-v2/01-teacher-guiding-student.png","staging/brisky-generated-v3/01-vocabulary-forgotten.png","staging/brisky-real/04-brisky-teachers.jpg","staging/brisky-generated-v3/04-level-assessment.png","staging/brisky-real/07-brisky-students.jpg"],cues:[
  {from:.02,to:2.20,text:"Cứ nhắc tới tiếng Anh"},{from:2.20,to:3.60,text:"là con rất sợ"},{from:3.60,to:7.64,text:"Ba mẹ đừng vội nghĩ con lười"},{from:7.68,to:10.30,text:"Con không học, không làm bài"},{from:10.30,to:12.80,text:"hay điểm kiểm tra thấp"},{from:12.80,to:15.40,text:"không có nghĩa là con lười"},
  {from:15.44,to:18.40,text:"Vấn đề thật sự là"},{from:18.40,to:21.56,text:"con mất gốc và thiếu định hướng"},{from:21.60,to:24.80,text:"Brisky tổ chức chương trình"},{from:24.80,to:27.40,text:"Bí mật lấy gốc tiếng Anh"},{from:27.40,to:31.58,text:"3 buổi Zoom cho cha mẹ lớp 3–9"},
  {from:31.62,to:34.20,text:"Thầy cung cấp cho ba mẹ"},{from:34.20,to:36.60,text:"một lộ trình học tập"},{from:36.60,to:38.80,text:"từ cơ bản đến nâng cao"},{from:38.80,to:40.76,text:"để biết con đang ở đâu"},{from:40.80,to:43.20,text:"Nếu ba mẹ quan tâm"},{from:43.20,to:46.00,text:"hãy nhấn nút đăng ký bên dưới"},{from:46.00,to:49.60,text:"Brisky sẽ liên hệ tư vấn kỹ hơn"}
 ]}
];

const keywords=new Set(["sợ","mất","gốc","8","điểm","lười","hổng","từ","vựng","ngữ","pháp","đọc","hiểu","3","buổi","zoom","lộ","trình","đăng","ký","brisky"]);

const Subtitle:React.FC<{cue:Cue}>=({cue})=>{const frame=useCurrentFrame();const {fps}=useVideoConfig();const duration=Math.round((cue.to-cue.from)*fps);const enter=spring({frame,fps,config:{damping:18,stiffness:230,mass:.68}});const exit=interpolate(frame,[Math.max(0,duration-6),duration],[1,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});const words=cue.text.split(/\s+/);return <AbsoluteFill style={{justifyContent:"flex-end",alignItems:"center",pointerEvents:"none"}}><div style={{position:"absolute",left:0,right:0,bottom:0,height:180,background:NAVY,boxShadow:"inset 0 1px 0 rgba(48,205,242,.28)"}}/><div style={{width:980,minHeight:180,padding:"20px 34px 18px",boxSizing:"border-box",opacity:enter*exit,transform:`translateY(${(1-enter)*16}px) scale(${.97+enter*.03})`,textAlign:"center",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}}><div style={{color:"rgba(224,235,243,.58)",fontSize:14,fontWeight:750,letterSpacing:4.2,marginBottom:7}}>THẦY QUYỀN CHIA SẺ</div><div style={{fontSize:40,fontWeight:800,lineHeight:1.15,letterSpacing:"-.025em",color:"white"}}>{words.map((word,i)=>{const clean=word.toLocaleLowerCase("vi").replace(/[.,!?;:]/g,"");const active=keywords.has(clean);return <React.Fragment key={`${word}-${i}`}><span style={{color:active?(i%2?CYAN:GOLD):"white"}}>{word}</span>{i<words.length-1?" ":""}</React.Fragment>})}</div><div style={{width:72,height:3,borderRadius:99,margin:"10px auto 0",background:`linear-gradient(90deg,${GOLD},${CYAN})`}}/></div></AbsoluteFill>};

const JoinCover:React.FC<{src:string;label:string}>=({src,label})=>{const frame=useCurrentFrame();const {fps}=useVideoConfig();const p=spring({frame,fps,config:{damping:18,stiffness:220,mass:.65}});return <div style={{position:"absolute",left:0,right:0,top:0,height:1740,overflow:"hidden",background:"#052448",opacity:p}}><Img src={staticFile(src)} style={{width:"100%",height:"100%",objectFit:"cover",transform:`scale(${1.04+frame*.0002})`}}/><AbsoluteFill style={{background:"linear-gradient(180deg,rgba(0,18,42,.04) 44%,rgba(0,18,42,.9) 100%)"}}/><div style={{position:"absolute",left:48,right:48,bottom:78,color:"white",fontSize:46,fontWeight:800,textAlign:"center",textShadow:"0 4px 16px #00152c"}}>{label}</div></div>};

const CompositionV3:React.FC<{index:number}>=({index})=>{useVietnameseFont();const frame=useCurrentFrame();const {fps}=useVideoConfig();const ad=ads[index];const scale=1.024+Math.sin(frame/86)*.011;const x=Math.sin(frame/117)*6;const y=Math.sin(frame/151)*3;const endFrom=Math.max(0,Math.round((ad.duration-3.8)*fps));return <AbsoluteFill style={{background:NAVY,color:"white",fontFamily:`'${VIETNAMESE_FONT_FAMILY}',sans-serif`,overflow:"hidden"}}><style>{vietnameseFontFaceCss}</style><div style={{position:"absolute",left:0,right:0,top:0,height:1740,overflow:"hidden"}}><Video src={staticFile(`staging/brisky-raw-ads/short-v3/${ad.id}-short-v3.mp4`)} style={{width:"100%",height:"100%",objectFit:"cover",transform:`translate(${x}px,${y}px) scale(${scale})`}}/><div style={{position:"absolute",top:0,left:0,height:6,width:`${Math.min(100,frame/(ad.duration*fps)*100)}%`,background:`linear-gradient(90deg,${GOLD},${CYAN})`}}/><Sequence from={0} durationInFrames={66}><AbsoluteFill style={{alignItems:"center",justifyContent:"flex-start",paddingTop:130,background:"linear-gradient(180deg,rgba(1,18,40,.66),transparent 42%)"}}><div style={{fontSize:62,lineHeight:1.05,fontWeight:850,textAlign:"center",textShadow:"0 5px 18px rgba(0,0,0,.8)"}}>{ad.hook}</div><Audio src={staticFile("staging/brisky-raw-ads/swoosh.mp3")} volume={.16}/></AbsoluteFill></Sequence>{ad.joins.map((join,i)=><Sequence key={`join-${i}`} from={Math.round((join-.75)*fps)} durationInFrames={Math.round(1.5*fps)}><JoinCover src={ad.assets[i%ad.assets.length]} label={ad.joinLabels[i]}/><Audio src={staticFile("staging/brisky-raw-ads/swoosh.mp3")} volume={.12}/></Sequence>)}</div><Audio src={staticFile("staging/brisky-raw-ads/music.mp3")} volume={.042} loop/>{ad.cues.map((cue,i)=><Sequence key={`cue-${i}`} from={Math.round(cue.from*fps)} durationInFrames={Math.max(8,Math.round((cue.to-cue.from)*fps))}><Subtitle cue={cue}/></Sequence>)}<Sequence from={endFrom} durationInFrames={Math.round(3.8*fps)}><div style={{position:"absolute",left:0,right:0,top:0,height:1740,background:"#062044",display:"flex",alignItems:"center",justifyContent:"center"}}><Img src={staticFile("staging/brisky-raw-ads/brisky-bimat-poster.png")} style={{width:"100%",height:"100%",objectFit:"contain"}}/></div><div style={{position:"absolute",left:0,right:0,bottom:0,height:180,background:NAVY,display:"flex",alignItems:"center",justifyContent:"center",color:GOLD,fontSize:46,fontWeight:850}}>NHẤN ĐĂNG KÝ NGAY</div><Audio src={staticFile("staging/brisky-raw-ads/ting.mp3")} volume={.18}/></Sequence></AbsoluteFill>};

export const BRISKY_SHORT_V3_DURATIONS=ads.map(a=>Math.ceil(a.duration*FPS));
export const BriskyShortV301=()=> <CompositionV3 index={0}/>;
export const BriskyShortV302=()=> <CompositionV3 index={1}/>;
export const BriskyShortV303=()=> <CompositionV3 index={2}/>;
export const BriskyShortV304=()=> <CompositionV3 index={3}/>;
export const BriskyShortV305=()=> <CompositionV3 index={4}/>;
