"use client";
import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowRight, BarChart3, BrainCircuit, ChevronLeft, ChevronRight, Clock3, CreditCard, Film, Home, Infinity as InfinityIcon, LoaderCircle, LogOut, Monitor, Play, RefreshCw, Search, Settings, ShieldCheck, SquarePlay, UserRound, Users } from 'lucide-react';
import { customerApi, StudioApiError, number, type CustomerUser } from './api';
import { AuthForm } from './AuthForm';
import { PasswordForm } from './PasswordForm';
import { StudioModal } from './StudioModal';
type Row=Record<string,unknown>;
type PageData={items:Row[];total:number;page:number;pageSize:number};
type Overview={stats:{customers:number;videos:number;activeVideos:number;paidVnd:number};days:number;series:{date:string;amount:number}[];recentJobs:Row[];services:{aiConfigured:boolean;sepayConfigured:boolean;renderMode:string}};
type Section='overview'|'customers'|'videos'|'orders'|'audit'|'account';
const sections=[{id:'overview',label:'Tổng quan',icon:Home},{id:'customers',label:'Khách hàng',icon:UserRound},{id:'videos',label:'Video',icon:Film},{id:'orders',label:'Thanh toán',icon:CreditCard},{id:'audit',label:'Lịch sử quản trị',icon:Clock3},{id:'account',label:'Tài khoản',icon:Settings}] as const;
const statuses:Record<string,string>={active:'Đang hoạt động',blocked:'Đã khóa',inspecting:'Kiểm tra nguồn',awaiting_confirmation:'Chờ xác nhận',queued:'Chờ dựng',running:'Đang dựng',local_running:'Dựng tại máy',done:'Hoàn tất',failed:'Thất bại',cancelled:'Đã hủy',pending:'Chờ thanh toán',paid:'Đã thanh toán',expired:'Hết hạn',tokens:'Điều chỉnh token',lock:'Khóa tài khoản',unlock:'Mở tài khoản'};
const s=(v:unknown)=>String(v ?? '');
const date=(v:unknown)=>new Date(Number(v)).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',dateStyle:'short',timeStyle:'short'});
const axisMoney=(v:number)=>v>=1000000?number(Math.round(v/100000)/10)+' tr đ':v>=1000?number(Math.round(v/100)/10)+'k đ':number(Math.round(v))+' đ';
const initials=(v:unknown)=>s(v).trim().split(/\s+/).slice(-2).map(x=>x[0]).join('').toUpperCase()||'KH';
function Badge({value}:{value:string}) {return <span className={`admin-status status-${value}`}><i />{statuses[value]||value}</span>;}
function Identity({row}:{row:Row}) {return <div className="admin-identity"><span className="admin-avatar">{initials(row.name||row.email)}</span><div><strong>{s(row.name||row.email)}</strong><small>{s(row.email)}</small></div></div>;}
function Empty({text='Chưa có dữ liệu phù hợp.'}:{text?:string}) {return <div className="admin-empty"><Film size={30}/><p>{text}</p></div>;}
export function AdminDashboard() {
 const [account,setAccount]=useState<CustomerUser|null>(null),[authReady,setAuthReady]=useState(false),[section,setSection]=useState<Section>('overview');
 const [days,setDays]=useState(30),[overview,setOverview]=useState<Overview|null>(null),[data,setData]=useState<PageData|null>(null);
 const [q,setQ]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0);
 const [loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[detail,setDetail]=useState<Row|null>(null),[detailKind,setDetailKind]=useState<Section>('customers');
 const [mutation,setMutation]=useState<{id:string;action:'tokens'|'lock'|'unlock';email:string;requestId:string}|null>(null),[delta,setDelta]=useState(''),[reason,setReason]=useState(''),[mutating,setMutating]=useState(false),[confirming,setConfirming]=useState(false),[mutationError,setMutationError]=useState('');
 useEffect(()=>{const value=new URLSearchParams(window.location.search).get('section');if(sections.some(x=>x.id===value)) setSection(value as Section);
   let live=true;customerApi<CustomerUser>('/me').then(u=>{if(live)setAccount(u);}).catch(e=>{if(live && (!(e instanceof StudioApiError)||e.status!==401))setError(e.message);}).finally(()=>{if(live)setAuthReady(true);});return()=>{live=false;};},[]);
 const navigate=useCallback((value:Section)=>{setSection(value);setData(null);setQ('');setSearch('');setStatus('');setPage(1);setDetail(null);setError('');setNotice('');window.history.replaceState(null,'','/studio/admin'+(value==='overview'?'':'?section='+value));},[]);
 useEffect(()=>{
   if(account?.role!=='admin'||section==='account')return;
   let live=true;setLoading(true);setError('');
   const endpoint=section==='overview'?'/admin/overview?days='+days:`/admin/${section}?page=${page}&q=${encodeURIComponent(search)}&status=${encodeURIComponent(status)}`;
   customerApi<Overview|PageData>(endpoint).then(result=>{if(!live)return;if(section==='overview')setOverview(result as Overview);else setData(result as PageData);}).catch(e=>{if(live){setError(e.message);if(e instanceof StudioApiError && e.status===401)setAccount(null);}}).finally(()=>{if(live)setLoading(false);});
   return()=>{live=false;};
 },[account?.id,account?.role,section,days,page,search,status,revision]);
 async function showDetail(kind:Section,row:Row) {
   setError('');try {const result=kind==='audit'?row:await customerApi<Row>(`/admin/${kind}/${s(row.id)}`);setDetailKind(kind);setDetail(result);}catch(e){setError(e instanceof Error?e.message:'Không tải được chi tiết');}
 }
 async function logout(){await customerApi('/auth/logout',{});window.location.assign('/studio');}
 function openMutation(action:'tokens'|'lock'|'unlock',row:Row) {setDetail(null);setMutation({id:s(row.id),email:s(row.email),action,requestId:crypto.randomUUID()});setReason('');setDelta('');setConfirming(false);setMutationError('');setNotice('');}
 async function submitMutation(event:FormEvent) {
   event.preventDefault();if(!mutation)return;
   if(!reason.trim()){setMutationError('Hãy nhập lý do thao tác.');return;}
   if(mutation.action==='tokens' && (!Number.isSafeInteger(Number(delta))||Number(delta)===0)){setMutationError('Nhập số token nguyên khác 0. Số âm để trừ token.');return;}
   if(!confirming){setConfirming(true);setMutationError('');return;}
   setMutating(true);setMutationError('');
   try {await customerApi(`/admin/customers/${mutation.id}/${mutation.action==='tokens'?'tokens':'status'}`,{requestId:mutation.requestId,reason:reason.trim(),...(mutation.action==='tokens'?{delta:Number(delta)}:{blocked:mutation.action==='lock'})});
     setNotice('Đã lưu thao tác và ghi lịch sử quản trị.');setMutation(null);setDetail(null);setRevision(x=>x+1);
   }catch(e){setMutationError(e instanceof Error?e.message:'Không lưu được thao tác');}finally{setMutating(false);}
 }
 const selected=sections.find(x=>x.id===section)!;
 if(!authReady)return <div className="aiev-admin admin-gate"><LoaderCircle className="studio-spin"/><p>Đang kiểm tra tài khoản…</p></div>;
 if(!account)return <div className="aiev-admin admin-gate"><div className="admin-auth"><Brand/><h1>Đăng nhập quản trị</h1>{error?<p className="admin-error">{error}</p>:null}<AuthForm success={u=>{if(u.role==='admin'){setAccount(u);setError('');}else window.location.assign('/studio');}}/><a className="admin-back" href="/studio">Quay lại Studio <ArrowRight size={16}/></a></div></div>;
 if(account.role!=='admin')return <div className="aiev-admin admin-gate"><ShieldCheck size={40}/><h1>Trang dành cho quản trị</h1><p>Tài khoản này không có quyền truy cập.</p><a className="admin-primary" href="/studio">Mở Studio <ArrowRight size={18}/></a></div>;
 return <div className="aiev-admin">
   <aside className="admin-sidebar"><Brand/><nav aria-label="Quản trị">{sections.map(({id,label,icon:Icon})=><button key={id} aria-current={section===id?'page':undefined} onClick={()=>navigate(id)}><Icon size={22}/><span>{label}</span></button>)}</nav><div className="admin-sidebar-account"><button className="admin-profile-link" onClick={()=>navigate('account')}><span className="admin-avatar">{initials(account.name)}</span><span><strong>{account.name}</strong><small>Quản trị viên</small></span></button><div className="admin-unlimited"><InfinityIcon size={22}/>Token không giới hạn</div></div></aside>
   <main className="admin-main"><header className="admin-header"><div><h1>{selected.label}</h1><p>{section==='overview'?'Theo dõi khách hàng, video và thanh toán.':section==='customers'?'Quản lý tài khoản và số dư token của khách hàng.':section==='videos'?'Theo dõi yêu cầu dựng và kết quả xử lý.':section==='orders'?'Đối chiếu đơn nạp và thanh toán đã nhận.':section==='audit'?'Mỗi thay đổi đều có người thực hiện và lý do.':'Thông tin và bảo mật tài khoản quản trị.'}</p></div><div className="admin-header-actions"><a className="admin-primary" href="/studio">Mở Studio <ArrowRight size={21}/></a><button className="admin-icon-button" aria-label="Cập nhật dữ liệu" disabled={loading} onClick={()=>setRevision(v=>v+1)}><RefreshCw size={22} className={loading?'studio-spin':''}/></button></div></header>
   {error?<p role="alert" className="admin-error">{error}</p>:null}{notice?<p role="status" className="admin-notice">{notice}</p>:null}{loading?<p className="admin-loading" role="status"><LoaderCircle className="studio-spin" size={17}/>Đang cập nhật dữ liệu…</p>:null}
   {section==='overview' && overview?<><div className="admin-stats">
     <Stat icon={<Users/>} label="Khách hàng" value={number(overview.stats.customers)} note="Tổng tài khoản khách hàng"/>
     <Stat icon={<SquarePlay/>} label="Lượt dựng" value={number(overview.stats.videos)} note={`Trong ${days} ngày`}/>
     <Stat icon={<Settings/>} label="Đang xử lý" value={number(overview.stats.activeVideos)} note="Gồm lượt dựng tại máy"/>
     <Stat icon={<BarChart3/>} label="Doanh thu" value={number(overview.stats.paidVnd)+' đ'} note={`Thực thu trong ${days} ngày`} money/>
   </div><div className="admin-analytics"><section className="admin-panel admin-chart-panel"><div className="admin-panel-header"><h2>Doanh thu thực thu</h2><div className="admin-period">{[7,30].map(n=><button key={n} aria-pressed={days===n} onClick={()=>setDays(n)}>{n} ngày</button>)}</div></div><RevenueChart series={overview.series}/></section><section className="admin-panel admin-services"><h2>Dịch vụ</h2><Service icon={<BrainCircuit/>} label="AI" detail="Kết nối AI đã cấu hình" ready={overview.services.aiConfigured}/><Service icon={<CreditCard/>} label="SePay" detail="Nhận giao dịch nạp token" ready={overview.services.sepayConfigured}/><Service icon={<Monitor/>} label="Dựng video" detail={overview.services.renderMode==='local'?'Dựng trên máy khách':'Dựng trên máy chủ'} ready/></section></div><section className="admin-panel"><div className="admin-panel-header"><h2>Hoạt động video</h2><button className="admin-text-button" onClick={()=>navigate('videos')}>Xem tất cả <ArrowRight size={17}/></button></div><VideoTable rows={overview.recentJobs} open={row=>void showDetail('videos',row)}/></section></>:null}
   {['customers','videos','orders','audit'].includes(section)?<section className="admin-panel admin-list-panel"><form className="admin-filters" onSubmit={e=>{e.preventDefault();setSearch(q);setPage(1);}}><label className="admin-search"><Search size={18}/><input aria-label="Tìm kiếm" placeholder={section==='customers'?'Tìm tên hoặc email…':section==='videos'?'Tìm email hoặc yêu cầu…':section==='orders'?'Tìm email hoặc mã đơn…':'Tìm người thực hiện, khách hàng hoặc lý do…'} value={q} onChange={e=>setQ(e.target.value)} maxLength={200}/></label><select aria-label="Lọc trạng thái" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Tất cả trạng thái</option>{(section==='customers'?['active','blocked']:section==='videos'?['awaiting_confirmation','local_running','done','failed','cancelled','inspecting','queued','running']:section==='orders'?['pending','paid','expired']:['tokens','lock','unlock']).map(v=><option key={v} value={v}>{statuses[v]}</option>)}</select><button className="admin-secondary" type="submit">Tìm kiếm</button></form>
    {data?<><DataTable kind={section} rows={data.items} open={row=>void showDetail(section,row)}/><div className="admin-pagination"><span>{number(data.total)} mục · Trang {page}/{Math.max(1,Math.ceil(data.total/25))}</span><div><button className="admin-icon-button" aria-label="Trang trước" disabled={page<=1||loading} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={18}/></button><button className="admin-icon-button" aria-label="Trang sau" disabled={page*25>=data.total||loading} onClick={()=>setPage(p=>p+1)}><ChevronRight size={18}/></button></div></div></>:!loading?<Empty/>:null}
   </section>:null}
   {section==='account'?<div className="admin-account-grid"><section className="admin-panel"><div className="admin-account-heading"><span className="admin-avatar large">{initials(account.name)}</span><div><h2>{account.name}</h2><p>{account.email}</p></div></div><div className="admin-account-badge"><ShieldCheck size={18}/>Quản trị viên</div><div className="admin-unlimited"><InfinityIcon size={24}/>Token không giới hạn</div><p className="admin-account-note">Miễn token cho quản trị khi chat và dựng video. Chi phí ước tính vẫn được ghi nhận để theo dõi.</p><button className="admin-secondary" onClick={()=>void logout().catch(e=>setError(e.message))}><LogOut size={18}/>Đăng xuất</button></section><section className="admin-panel"><h2>Đổi mật khẩu</h2><PasswordForm/></section></div>:null}
   </main>
   {detail?<StudioModal title={detailKind==='customers'?'Chi tiết khách hàng':detailKind==='videos'?'Chi tiết video':detailKind==='orders'?'Chi tiết đơn nạp':'Chi tiết thao tác'} close={()=>setDetail(null)}><Detail kind={detailKind} data={detail} mutate={openMutation}/></StudioModal>:null}
   {mutation?<StudioModal title={statuses[mutation.action]} close={()=>{if(!mutating)setMutation(null);}}><form className="admin-mutation studio-form" onSubmit={submitMutation}><p>Khách hàng: <strong>{mutation.email}</strong></p>{confirming?<div className="admin-confirmation"><h3>Xác nhận thay đổi</h3><p>{mutation.action==='tokens'?`${Number(delta)>0?'Cộng':'Trừ'} ${number(Math.abs(Number(delta)))} token.`:mutation.action==='lock'?'Khóa tài khoản và đăng xuất các phiên hiện có.':'Mở lại quyền đăng nhập và sử dụng.'}</p><p>Lý do: {reason}</p><small>Thao tác sẽ được ghi vào lịch sử quản trị.</small></div>:<>{mutation.action==='tokens'?<label>Số token điều chỉnh<input aria-label="Số token điều chỉnh" type="number" step="1" required value={delta} onChange={e=>setDelta(e.target.value)}/><small>Số dương để cộng, số âm để trừ.</small></label>:null}<label>Lý do<textarea aria-label="Lý do" required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label></>}{mutationError?<p className="admin-error" role="alert">{mutationError}</p>:null}<div className="admin-form-actions"><button type="button" className="admin-secondary" disabled={mutating} onClick={()=>confirming?setConfirming(false):setMutation(null)}>{confirming?'Chỉnh lại':'Hủy'}</button><button className="admin-primary" disabled={mutating}>{mutating?'Đang lưu…':confirming?'Xác nhận thay đổi':'Tiếp tục'}</button></div></form></StudioModal>:null}
 </div>;
}
function Brand(){return <a className="admin-brand" href="/studio/admin"><Play size={43} strokeWidth={2.5}/><span>AIEV Studio<small>Quản trị</small></span></a>;}
function Stat({icon,label,value,note,money}:{icon:ReactNode;label:string;value:string;note:string;money?:boolean}) {return <div className="admin-stat"><span className="admin-stat-icon">{icon}</span><div><span>{label}</span><strong className={money?'money':''}>{value}</strong><small>{note}</small></div></div>;}
function Service({icon,label,detail,ready}:{icon:ReactNode;label:string;detail:string;ready:boolean}) {return <div className="admin-service"><span className="admin-service-icon">{icon}</span><div><strong>{label}</strong><small>{detail}</small></div><span className={ready?'configured':'unconfigured'}><i/>{label==='Dựng video'?'Tại thiết bị':ready?'Đã cấu hình':'Chưa cấu hình'}</span></div>;}
function RevenueChart({series}:{series:Overview['series']}) {
 const max=Math.max(100000,...series.map(r=>r.amount)),w=800,h=240,left=110,right=760,top=20,bottom=195;
 const points=series.map((r,i)=>[left+i/(series.length-1||1)*(right-left),bottom-r.amount/max*(bottom-top)]);
 const line=points.map(([x,y],i)=>(i?'L':'M')+x.toFixed(1)+','+y.toFixed(1)).join(' ');
 const labels=[0,Math.floor((series.length-1)/3),Math.floor((series.length-1)*2/3),series.length-1];
 return <div className="admin-chart"><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Biểu đồ doanh thu thực thu theo ngày">{[0,1,2,3].map(i=>{const y=bottom-i/3*(bottom-top);return <g key={i}><line x1={left} x2={right} y1={y} y2={y}/><text x={left-12} y={y+4} textAnchor="end">{axisMoney(max*i/3)}</text></g>;})}<path d={`${line} L${right},${bottom} L${left},${bottom} Z`} className="admin-chart-area"/><path d={line} className="admin-chart-line"/>{labels.map((idx,i)=><text key={i} x={points[idx]?.[0] || left} y={226} textAnchor="middle">{series[idx]?.date.slice(8)+'/'+series[idx]?.date.slice(5,7)}</text>)}</svg>{series.every(r=>r.amount===0)?<p>Chưa có doanh thu thực thu trong khoảng thời gian này.</p>:null}</div>;
}
function VideoTable({rows,open}:{rows:Row[];open:(row:Row)=>void}) {return rows.length?<div className="admin-table-wrap"><table><thead><tr><th>Khách hàng</th><th>Yêu cầu</th><th>Trạng thái</th><th>Thời gian</th><th/></tr></thead><tbody>{rows.map(row=><tr key={s(row.id)}><td><Identity row={row}/></td><td><span className="admin-prompt">{s(row.prompt)}</span><small>{Math.ceil(Number(row.duration))} giây · Ước tính {number(Number(row.tokens))} token</small></td><td><Badge value={s(row.status)}/></td><td className="admin-nowrap">{date(row.created_at)}</td><td><button className="admin-text-button" onClick={()=>open(row)}>Chi tiết</button></td></tr>)}</tbody></table></div>:<Empty text="Chưa có yêu cầu video."/>;}
function DataTable({kind,rows,open}:{kind:Section;rows:Row[];open:(row:Row)=>void}) {
 if(kind==='videos')return <VideoTable rows={rows} open={open}/>;
 if(!rows.length)return <Empty/>;
 const headers=kind==='customers'?['Khách hàng','Token','Trạng thái']:kind==='orders'?['Mã đơn / Khách hàng','Số tiền','Trạng thái','Thời gian']:['Người thực hiện / Khách hàng','Thao tác','Lý do','Thời gian'];
 return <div className="admin-table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}<th/></tr></thead><tbody>{rows.map(row=><tr key={s(row.id)}>{kind==='customers'?<><td><Identity row={row}/></td><td>{number(Number(row.balance))} token</td><td><Badge value={row.blocked?'blocked':'active'}/></td></>:kind==='orders'?<><td><strong>{s(row.code)}</strong><small>{s(row.email)}</small></td><td>{number(Number(row.amount))} đ<small>{number(Number(row.tokens))} token</small></td><td><Badge value={s(row.status)}/></td><td>{date(row.created_at)}</td></>:<><td>{s(row.actorEmail)}<small>{s(row.targetEmail)}</small></td><td><Badge value={s(row.action)}/></td><td><span className="admin-prompt">{s(row.reason)}</span></td><td>{date(row.created_at)}</td></>}<td><button className="admin-text-button" onClick={()=>open(row)}>Chi tiết</button></td></tr>)}</tbody></table></div>;
}
function Detail({kind,data,mutate}:{kind:Section;data:Row;mutate:(action:'tokens'|'lock'|'unlock',row:Row)=>void}) {
 if(kind==='customers') {const account=data.account as Row,jobs=data.jobs as Row[],orders=data.orders as Row[],ledger=data.ledger as Row[];return <div className="admin-detail"><Identity row={account}/><dl><dt>Trạng thái</dt><dd><Badge value={account.blocked?'blocked':'active'}/></dd><dt>Số dư</dt><dd>{number(Number(account.balance))} token</dd></dl>{account.role==='customer'?<div className="admin-form-actions"><button className="admin-primary" onClick={()=>mutate('tokens',account)}>Điều chỉnh token</button><button className="admin-secondary" onClick={()=>mutate(account.blocked?'unlock':'lock',account)}>{account.blocked?'Mở tài khoản':'Khóa tài khoản'}</button></div>:null}<h3>Video gần đây</h3>{jobs.length?jobs.map(j=><div className="admin-detail-row" key={s(j.id)}><span>{s(j.prompt)}</span><Badge value={s(j.status)}/></div>):<p>Chưa có video.</p>}<h3>Đơn nạp gần đây</h3>{orders.length?orders.map(o=><div className="admin-detail-row" key={s(o.id)}><span>{s(o.code)}<small>{number(Number(o.amount))} đ</small></span><Badge value={o.status==='pending'&&Number(o.expires)<Date.now()?'expired':s(o.status)}/></div>):<p>Chưa có đơn nạp.</p>}<h3>Lịch sử token</h3>{ledger.length?ledger.map((r,i)=><div className="admin-detail-row" key={i}><span>{({purchase:'Nạp token',reserve:'Dựng video',chat:'Chat AI',refund:'Hoàn phí dựng',chat_refund:'Hoàn phí chat',admin_adjustment:'Điều chỉnh quản trị'} as Record<string,string>)[s(r.kind)]||s(r.kind)}<small>{date(r.created_at)}</small></span><strong>{Number(r.delta)>0?'+':''}{number(Number(r.delta))}</strong></div>):<p>Chưa có giao dịch.</p>}</div>;}
 if(kind==='audit') {const p=data.payload as Row;return <div className="admin-detail"><dl><dt>Người thực hiện</dt><dd>{s(data.actorEmail)}</dd><dt>Khách hàng</dt><dd>{s(data.targetEmail)}</dd><dt>Thao tác</dt><dd>{statuses[s(data.action)]}</dd><dt>Thời gian</dt><dd>{date(data.created_at)}</dd><dt>Lý do</dt><dd>{s(data.reason)}</dd><dt>Số dư trước / sau</dt><dd>{number(Number(p.beforeBalance))} / {number(Number(p.afterBalance))} token</dd><dt>Trạng thái trước / sau</dt><dd>{p.beforeBlocked?'Đã khóa':'Hoạt động'} / {p.afterBlocked?'Đã khóa':'Hoạt động'}</dd></dl></div>;}
 return <div className="admin-detail"><dl><dt>Khách hàng</dt><dd>{s(data.email)}</dd><dt>Trạng thái</dt><dd><Badge value={s(data.status)}/></dd><dt>Thời gian tạo</dt><dd>{date(data.created_at)}</dd>{kind==='videos'?<><dt>Yêu cầu</dt><dd>{s(data.prompt)}</dd><dt>Đang ở bước</dt><dd>{s(data.stage)}</dd><dt>Thời lượng nguồn</dt><dd>{Math.ceil(Number(data.duration))} giây</dd><dt>Token ước tính / thực trừ</dt><dd>{number(Number(data.tokens))} / {number(Number(data.chargedTokens))}</dd>{data.error?<><dt>Lỗi</dt><dd>{s(data.error)}</dd></>:null}<dt>Vị trí kết quả</dt><dd>{data.output==='local.mp4'?'Trên máy người dùng':data.output?'Trên máy chủ':'Chưa có kết quả'}</dd></>:<><dt>Mã đơn</dt><dd>{s(data.code)}</dd><dt>Số tiền</dt><dd>{number(Number(data.amount))} đ</dd><dt>Token</dt><dd>{number(Number(data.tokens))}</dd><dt>Hết hạn</dt><dd>{date(data.expires)}</dd><dt>Đã nhận tiền</dt><dd>{data.paidAt?date(data.paidAt):'Chưa ghi nhận'}</dd></>}</dl></div>;
}
